// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from '@dotenvx/dotenvx';
import { defineConfig } from 'prisma/config';

config({ path: ['.env.local', '.env'] });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: `npx tsx prisma/seed.ts`,
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
