import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { InfoBanner } from '@/components';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`
        ${geistSans.variable}
        ${geistMono.variable}
        h-full antialiased
      `}
    >
      <body className="flex min-h-full flex-col">
        <InfoBanner className="m-0!">
          This is a mockup. No data is loaded.
        </InfoBanner>
        {children}
      </body>
    </html>
  );
}
